FUNCTION_BLOCK Fnc_13
VAR_INPUT
    input0: BOOL;
    input1: BOOL;
    input2: BOOL;
    input3: BOOL;
    input4: BOOL;
    input5: BOOL;
    input6: BOOL;
    input7: BOOL;
    input8: BOOL;
    input9: BOOL;
    input10: BOOL;
    input11: BOOL;
    input12: BOOL;
    input13: BOOL;
    input14: BOOL;
    input15: BOOL;
    input16: BOOL;
    input17: BOOL;
    input18: BOOL;
    input19: BOOL;
END_VAR
VAR_OUTPUT
    output1: BOOL;
END_VAR
VAR
END_VAR
VAR_TEMP
END_VAR
output1 :=
(((((((((NOT(input0) OR NOT(input1)) OR NOT(input2)) OR NOT(input3)) OR NOT(input4)) OR NOT(input5)) OR NOT(input6)) OR NOT(input7)) OR NOT(input8)) OR NOT(input9))
OR
(((((((((NOT(input10) OR NOT(input11)) OR NOT(input12)) OR NOT(input13)) OR NOT(input14)) OR NOT(input15)) OR NOT(input16)) OR NOT(input17)) OR NOT(input18)) OR NOT(input19))
END_FUNCTION_BLOCK
VAR_GLOBAL CONSTANT
END_VAR
VAR_GLOBAL
END_VAR
