FUNCTION_BLOCK Fnc_14
VAR_INPUT
    input0: BOOL;
    input1: BOOL;
    input2: BOOL;
    input3: BOOL;
    input4: BOOL;
    input5: BOOL;
    input6: BOOL;
    input7: BOOL;
    input8: BOOL;
    input9: BOOL;
    input10: BOOL;
    input11: BOOL;
    input12: BOOL;
    input13: BOOL;
    input14: BOOL;
    input15: BOOL;
    input16: BOOL;
    input17: BOOL;
    input18: BOOL;
    input19: BOOL;
END_VAR
VAR_OUTPUT
    output1: BOOL;
END_VAR
VAR
END_VAR
VAR_TEMP
END_VAR
output1 :=
NOT(
(((((((((input0 AND input1) AND input2) AND input3) AND input4) AND input5) AND input6) AND input7) AND input8) AND input9)
AND
(((((((((input10 AND input11) AND input12) AND input13) AND input14) AND input15) AND input16) AND input17) AND input18) AND input19)
)
END_FUNCTION_BLOCK
VAR_GLOBAL CONSTANT
END_VAR
VAR_GLOBAL
END_VAR
